use_frameworks!
platform :ios, '10.0'

target 'ParticleConnect_Example' do
  pod 'ParticleConnect', :path => '../'

  target 'ParticleConnect_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
